# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_auto_20170923_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puclicip_id', models.CharField(max_length=40, null=True, verbose_name='弹性IP-ID')),
                ('publicip_status', models.CharField(max_length=20, null=True, verbose_name='状态')),
                ('publicip_type', models.CharField(max_length=10, null=True, verbose_name='IP类型')),
                ('publicip', models.GenericIPAddressField(null=True, verbose_name='弹性IP')),
                ('privateip', models.GenericIPAddressField(null=True, verbose_name='私有IP')),
                ('project_id', models.CharField(max_length=40, null=True, verbose_name='项目ID')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('bandwidth_id', models.CharField(max_length=40, null=True, verbose_name='带宽ID')),
                ('bandwidth_type', models.CharField(max_length=10, null=True, verbose_name='带宽类型')),
                ('bandwidth_size', models.IntegerField(max_length=4, null=True, verbose_name='带宽大小')),
                ('bandwidth_name', models.CharField(max_length=128, null=True, verbose_name='带宽名称')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'verbose_name': '弹性IP',
                'verbose_name_plural': '弹性IP',
                'db_table': 'hw_vpc',
            },
        ),
    ]
