# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0002_auto_20170923_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpc',
            name='account_name',
            field=models.CharField(max_length=20, null=True, verbose_name='账户'),
        ),
    ]
