# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0003_vpc_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpc',
            name='region',
            field=models.CharField(choices=[('cn-north-1', '华北1'), ('cn-south-1', '华南1'), ('cn-east-2', '华东2')], default='cn-north-1', max_length=32, verbose_name='区域'),
        ),
    ]
