# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0005_auto_20170923_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpc',
            name='bandwidth_type',
            field=models.CharField(choices=[('WHOLE', '共享'), ('PER', '独享')], max_length=10, null=True, verbose_name='带宽类型'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='publicip_type',
            field=models.CharField(choices=[('5_bgp', '动态'), ('5_sbgp', '静态')], max_length=10, null=True, verbose_name='IP类型'),
        ),
    ]
