# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0009_auto_20170924_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpc',
            name='publicip_type',
            field=models.CharField(choices=[('5_bgp', '动态BGP'), ('5_sbgp', '静态BGP')], max_length=10, null=True, verbose_name='IP类型'),
        ),
    ]
