# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20170923_1655'),
        ('vpc', '0010_auto_20170924_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicip_id', models.CharField(max_length=40, null=True, verbose_name='弹性IP-ID')),
                ('publicip_status', models.CharField(max_length=20, null=True, verbose_name='状态')),
                ('publicip_type', models.CharField(choices=[('5_bgp', '动态BGP'), ('5_sbgp', '静态BGP')], max_length=10, null=True, verbose_name='IP类型')),
                ('publicip', models.GenericIPAddressField(null=True, verbose_name='弹性IP')),
                ('project_id', models.CharField(max_length=40, null=True, verbose_name='项目ID')),
                ('create_time', models.CharField(max_length=40, null=True, verbose_name='创建时间(UTC)')),
                ('bandwidth_size', models.IntegerField(null=True, verbose_name='带宽大小')),
                ('account_name', models.CharField(max_length=20, null=True, verbose_name='账户')),
                ('region', models.CharField(choices=[('cn-north-1', '华北1'), ('cn-south-1', '华南1'), ('cn-east-2', '华东2')], default='cn-north-1', max_length=32, verbose_name='区域')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'verbose_name': '创建指定IP',
                'verbose_name_plural': '创建指定IP',
                'db_table': 'hw_createip',
            },
        ),
    ]
