# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0011_createip'),
    ]

    operations = [
        migrations.AddField(
            model_name='createip',
            name='bandwidth_name',
            field=models.CharField(max_length=128, null=True, verbose_name='带宽名称'),
        ),
        migrations.AddField(
            model_name='createip',
            name='bandwidth_type',
            field=models.CharField(choices=[('WHOLE', '共享'), ('PER', '独享')], max_length=10, null=True, verbose_name='带宽类型'),
        ),
    ]
