# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0016_remove_createip_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createip',
            old_name='bandwidth_type',
            new_name='bandwidth_share_type',
        ),
    ]
