# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0017_auto_20170925_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createip',
            name='bandwidth_charge_mode',
            field=models.CharField(blank=True, choices=[('traffic', '按流量计费'), ('bandwidth', '按带宽计费')], help_text='独享带宽必填，共享带宽不填写', max_length=10, null=True, verbose_name='带宽计费方式'),
        ),
    ]
