# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0019_auto_20170925_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createip',
            name='result',
            field=models.CharField(choices=[('200', '状态码200，命令下发成功，请检查IP是否创建成功'), ('409', '错误码409，IP地址已被占用，创建失败'), ('400', '错误码400，参数错误，请检查填写项')], max_length=128, null=True, verbose_name='创建结果'),
        ),
    ]
