# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0020_auto_20170925_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createip',
            name='bandwidth_size',
            field=models.IntegerField(blank=True, help_text='填写数字，范围1~300，单位默认M,共享带宽不填写', null=True, verbose_name='带宽大小'),
        ),
    ]
