# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0021_auto_20170925_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createip',
            name='bandwidth_share_id',
            field=models.CharField(blank=True, help_text='独享带宽不填写，共享带宽填写', max_length=40, null=True, verbose_name='共享带宽ID'),
        ),
        migrations.AlterField(
            model_name='createip',
            name='bandwidth_size',
            field=models.IntegerField(blank=True, help_text='填写数字，范围1~300M，共享带宽不填写', null=True, verbose_name='带宽大小'),
        ),
        migrations.AlterField(
            model_name='createip',
            name='publicip_type',
            field=models.CharField(choices=[('5_bgp', '动态BGP'), ('5_sbgp', '静态BGP')], help_text="<font color='red'>* 为必填项</font>", max_length=10, null=True, verbose_name='IP类型'),
        ),
    ]
