# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0022_auto_20170926_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createip',
            name='bandwidth_charge_mode',
            field=models.CharField(blank=True, choices=[('traffic', '按流量计费'), ('bandwidth', '按带宽计费')], help_text="<font color='blue'>独享带宽填写</font>，<font color='red'>共享带宽留空</font>", max_length=10, null=True, verbose_name='带宽计费方式'),
        ),
        migrations.AlterField(
            model_name='createip',
            name='bandwidth_name',
            field=models.CharField(blank=True, help_text="<font color='blue'>独享带宽填写</font>，<font color='red'>共享带宽留空</font", max_length=128, null=True, verbose_name='带宽名称'),
        ),
        migrations.AlterField(
            model_name='createip',
            name='bandwidth_share_id',
            field=models.CharField(blank=True, help_text="<font color='blue'>独享带宽留空</font>，<font color='red'>共享带宽填写</font>", max_length=40, null=True, verbose_name='共享带宽ID'),
        ),
        migrations.AlterField(
            model_name='createip',
            name='bandwidth_size',
            field=models.IntegerField(blank=True, help_text="<font color='blue'>独享带宽，填写数字，范围1~300M</font>，<font color='red'>共享带宽留空</font>", null=True, verbose_name='带宽大小'),
        ),
    ]
