# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0024_auto_20170926_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createip',
            name='bandwidth_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='带宽名称'),
        ),
    ]
