# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0027_auto_20170926_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createip',
            name='publicip_status',
        ),
    ]
