# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0028_remove_createip_publicip_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createip',
            options={'verbose_name': '创建IP', 'verbose_name_plural': '创建IP'},
        ),
    ]
