# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0029_auto_20170926_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createip',
            name='bandwidth_share_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpc.Vpc', to_field='bandwidth_id'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='bandwidth_id',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='带宽ID'),
        ),
    ]
