# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0030_auto_20170930_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createip',
            name='bandwidth_share_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpc.Vpc'),
        ),
    ]
