# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0031_auto_20170930_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createip',
            name='bandwidth_share_id',
        ),
    ]
