# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0032_remove_createip_bandwidth_share_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='createip',
            name='bandwidth_share_id',
            field=models.CharField(blank=True, help_text="<font color='blue'>独享带宽留空</font>，<font color='red'>共享带宽填写</font>", max_length=40, null=True, verbose_name='共享带宽ID'),
        ),
    ]
