# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0033_createip_bandwidth_share_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createip',
            name='account',
        ),
        migrations.DeleteModel(
            name='Createip',
        ),
    ]
