# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20170926_0016'),
        ('vpc', '0034_auto_20170930_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicip_id', models.CharField(max_length=40, null=True, verbose_name='弹性IP-ID')),
                ('publicip_type', models.CharField(choices=[('5_bgp', '动态BGP'), ('5_sbgp', '静态BGP')], help_text="<font color='red'>* 为必填项</font>", max_length=10, null=True, verbose_name='IP类型')),
                ('publicip', models.GenericIPAddressField(blank=True, help_text='指定ip地址创建，留空则随机创建ip', null=True, verbose_name='弹性IP')),
                ('create_time', models.CharField(max_length=40, null=True, verbose_name='创建时间(UTC)')),
                ('bandwidth_share_type', models.CharField(choices=[('WHOLE', '共享'), ('PER', '独享')], max_length=10, null=True, verbose_name='带宽类型')),
                ('bandwidth_size', models.IntegerField(blank=True, help_text="<font color='blue'>独享带宽，填写数字，范围1~300M</font>，<font color='red'>共享带宽留空</font>", null=True, verbose_name='带宽大小')),
                ('bandwidth_name', models.CharField(blank=True, help_text="<font color='blue'>独享带宽填写</font>，<font color='red'>共享带宽留空</font>", max_length=128, null=True, verbose_name='带宽名称')),
                ('bandwidth_charge_mode', models.CharField(blank=True, choices=[('traffic', '按流量计费'), ('bandwidth', '按带宽计费')], help_text="<font color='blue'>独享带宽填写</font>，<font color='red'>共享带宽留空</font>", max_length=10, null=True, verbose_name='带宽计费方式')),
                ('account_name', models.CharField(help_text='填写云账户中已经配置的帐户名', max_length=20, null=True, verbose_name='账户')),
                ('region', models.CharField(choices=[('cn-north-1', '华北1'), ('cn-south-1', '华南1'), ('cn-east-2', '华东2')], max_length=32, null=True, verbose_name='区域')),
                ('result', models.CharField(choices=[('200', '状态码200，命令下发成功，请检查IP是否创建成功'), ('409', '错误码409，IP地址已被占用，创建失败'), ('400', '错误码400，参数错误，请检查填写项')], max_length=128, null=True, verbose_name='创建结果')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('bandwidth_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpc.Vpc')),
            ],
            options={
                'verbose_name': '创建IP',
                'verbose_name_plural': '创建IP',
                'db_table': 'hw_createip',
            },
        ),
    ]
