# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0036_auto_20170930_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createip',
            name='bandwidth_share_name',
        ),
        migrations.AlterField(
            model_name='createip',
            name='bandwidth_name',
            field=models.CharField(help_text="<font color='blue'>独享带宽填写新建的带宽名称</font>，<font color='red'>共享带宽填写已有的共享带宽名称</font>", max_length=128, null=True, verbose_name='带宽名称'),
        ),
    ]
