# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0037_auto_20170930_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='createip',
            name='bandwidth_share_id',
            field=models.CharField(blank=True, help_text="<font color='blue'>独享带宽留空</font>，<font color='red'>共享带宽填写</font>", max_length=40, null=True, verbose_name='共享带宽ID'),
        ),
        migrations.AlterField(
            model_name='createip',
            name='bandwidth_name',
            field=models.CharField(blank=True, help_text="<font color='blue'>独享带宽填写</font>，<font color='red'>共享带宽留空</font>", max_length=128, null=True, verbose_name='带宽名称'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='bandwidth_id',
            field=models.CharField(max_length=40, null=True, verbose_name='带宽ID'),
        ),
    ]
