# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0041_auto_20170930_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createip',
            name='result',
            field=models.CharField(choices=[('1', '参数错误，带宽名称，大小，计费方式，必须填写'), ('2', '参数错误，共享带宽ID必须填写，请在弹性IP页面查找ID'), ('200', '状态码200，命令下发成功，请在弹性IP页面中检查IP'), ('409', '错误码409，IP地址已被占用，创建失败'), ('400', '错误码400，参数错误，请检查填写项')], max_length=128, null=True, verbose_name='创建结果'),
        ),
    ]
