# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpc', '0045_auto_20171010_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createip',
            name='create_time',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='create_time',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
    ]
