# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20, verbose_name='账户名')),
                ('user_name', models.CharField(default='若使用帐户名登录，此项填写账户名', max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('pidcn_north_1', models.CharField(default='在我的凭证中查看项目列表获取', max_length=40, verbose_name='项目ID-华北1')),
                ('pidcn_east_2', models.CharField(max_length=40, verbose_name='项目ID-华东2')),
                ('pidcn_south_1', models.CharField(max_length=40, verbose_name='项目ID-华南1')),
            ],
            options={
                'verbose_name': '云账户',
                'verbose_name_plural': '云账户',
                'db_table': 'hw_account',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('region', models.CharField(max_length=32)),
                ('up_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'hw_token',
            },
        ),
    ]
