# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170914_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AddField(
            model_name='account',
            name='token_up_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='tokencn_east_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='tokencn_north_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='tokencn_south_1',
            field=models.TextField(null=True),
        ),
    ]
