# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170916_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='token_up_time',
        ),
        migrations.AddField(
            model_name='account',
            name='token_exp_time',
            field=models.DateTimeField(null=True, verbose_name='token-有效'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tokencn_east_2',
            field=models.TextField(null=True, verbose_name='token-华东2'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tokencn_north_1',
            field=models.TextField(null=True, verbose_name='token-华北1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tokencn_south_1',
            field=models.TextField(null=True, verbose_name='token-华南1'),
        ),
    ]
