# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170916_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='token_exp_time',
        ),
    ]
