# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_token_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token_up_time',
            field=models.DateTimeField(null=True, verbose_name='token-有效(UTC)'),
        ),
    ]
