# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170916_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token_up_time',
            field=models.DateTimeField(null=True, verbose_name='Token-有效(UTC)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tokencn_east_2',
            field=models.TextField(null=True, verbose_name='Token-华东2'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tokencn_south_1',
            field=models.TextField(null=True, verbose_name='Token-华南1'),
        ),
    ]
