# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20170923_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_name',
            field=models.CharField(help_text='若使用主帐户登录，填写账户名，否则填写子用户名', max_length=20, verbose_name='用户名'),
        ),
    ]
