# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20170925_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(help_text='登录用户名使用的密码', max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pidcn_east_2',
            field=models.CharField(help_text="在控制台'我的凭证'中查看项目列表获取", max_length=40, verbose_name='项目ID-华东2'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pidcn_north_1',
            field=models.CharField(help_text="在控制台'我的凭证'中查看项目列表获取", max_length=40, verbose_name='项目ID-华北1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pidcn_south_1',
            field=models.CharField(help_text="在控制台'我的凭证'中查看项目列表获取", max_length=40, verbose_name='项目ID-华南1'),
        ),
    ]
