# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20170926_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(help_text="登录华为云的主帐户名,<font color='red'> * 为必填项</font>", max_length=20, unique=True, verbose_name='账户名'),
        ),
    ]
