# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20170926_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token_up_time',
            field=models.DateTimeField(null=True, verbose_name='Token-失效'),
        ),
    ]
