# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='ecs_id',
            field=models.CharField(default='例：c90ab83a-6cdd-4404-8578-05fa965cfb12', max_length=40, unique=True, verbose_name='主机ID'),
        ),
    ]
