# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecs', '0002_auto_20170914_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecs',
            options={'verbose_name': '云主机', 'verbose_name_plural': '云主机'},
        ),
        migrations.RemoveField(
            model_name='ecs',
            name='delete_ecs_tag',
        ),
        migrations.RemoveField(
            model_name='ecs',
            name='shut_ecs_tag',
        ),
        migrations.AlterModelTable(
            name='ecs',
            table='hw_ecs',
        ),
    ]
