# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170916_2356'),
        ('ecs', '0003_auto_20170920_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecs',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
