# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecs', '0004_ecs_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
