# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs', '0006_auto_20170921_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='ecs_name',
            field=models.CharField(default='例：dwx411174_test', max_length=128, null=True, verbose_name='主机名称'),
        ),
    ]
