# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs', '0007_auto_20170921_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='ecs_id',
            field=models.CharField(default='c90ab83a-6cdd-4404-8578-05fa965cfb12', max_length=40, verbose_name='主机ID'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='ecs_name',
            field=models.CharField(max_length=128, null=True, verbose_name='主机名称'),
        ),
    ]
