# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecs', '0008_auto_20170921_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecs',
            old_name='ecs_status_tag',
            new_name='ecs_is_active',
        ),
    ]
