# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs', '0009_auto_20170921_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecs',
            name='private_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='私网地址'),
        ),
        migrations.AddField(
            model_name='ecs',
            name='public_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='公网地址'),
        ),
    ]
