# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0014_auto_20171014_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rds_name', models.CharField(max_length=128, null=True, verbose_name='实例名称')),
                ('rds_id', models.CharField(max_length=40, null=True, verbose_name='实例ID')),
                ('rds_status', models.CharField(max_length=20, null=True, verbose_name='状态')),
                ('region', models.CharField(choices=[('cn-north-1', '华北1'), ('cn-south-1', '华南1'), ('cn-east-2', '华东2')], default='cn-north-1', max_length=32, verbose_name='区域')),
                ('rds_host', models.GenericIPAddressField(null=True, verbose_name='IP地址')),
                ('rds_port', models.CharField(max_length=10, null=True, verbose_name='端口')),
                ('rds_type', models.CharField(max_length=20, null=True, verbose_name='类型')),
                ('rds_delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('account_name', models.CharField(max_length=20, null=True, verbose_name='账户')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'verbose_name': '关系型数据库',
                'verbose_name_plural': '关系型数据库',
                'db_table': 'hw_rds',
            },
        ),
    ]
